# Generated by Django 4.2.7 on 2023-11-26 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_pu_consultation_fundings_alter_pu_edp_fundings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subparameterscore',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
