# Generated by Django 4.2.7 on 2023-12-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_institutionscore_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionscore',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
